[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies.bevy]
version = "0.9"

[dependencies.bevy_rapier3d]
version = "0.19"
features = ["debug-render"]
